# -*- coding: utf-8 -*-
"""addition

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aBDBJH6B-GP8WBGEtaQEh6V0AF5Nux9A
"""

# Python3 program to add two numbers
  
num1 = 15
num2 = 12
  
# Adding two nos
sum = num1 + num2
  
# printing values
print("Sum of {0} and {1} is {2}" .format(num1, num2, sum))

# Python3 program to add two numbers
  
number1 = input("First number: ")
number2 = input("\nSecond number: ")
  
# Adding two numbers
# User might also enter float numbers
sum = float(number1) + float(number2)
  
# Display the sum
# will print value in float
print("The sum of {0} and {1} is {2}" .format(number1, number2, sum))